### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by Yoric** [sgodwincs/webidl-rs#11] opened 2018-03-09 16:29 UTC
I'm trying to land as part of Firefox a package that depends on webidl-rs. That's unfortunately not possible because of the following files:

- 1.9M	lalrpop-snap/src/newparser.rs
- 1.9M	lalrpop-snap/src/parser/lrgrammar.rs
- 1.9M	lalrpop/src/newparser.rs
- 2.3M	lalrpop/src/parser/lrgrammar.rs
- 832K	webidl/src/parser/grammar.rs
- 177K	webidl/tests/mozilla_webidl.zip

It would be great if we could find a way to get rid of these files.

For mozilla_webidl.zip and grammar.rs, I believe it's just a matter of adding an `exclude` in Cargo.toml. For lalrpop-*, I believe that more recent versions don't contain such huge files anymore.

**Comment by Yoric** [comment] 2018-03-14 18:17
Apparently, I made a mistake and this doesn't remove all the files I thought it would.

Blocked by https://github.com/lalrpop/lalrpop/issues/333.

**Comment by sgodwincs** [comment] 2018-03-14 19:56
Are you sure `grammar.rs` is still included? It doesn't seem to be there from what I see.

**Comment by mbrubeck** [comment] 2018-03-14 20:06
I believe #13 fixes the cause of `grammar.rs` sometimes ending up in the vendor directory.  This could happen when `cargo build` builds the file out of the Cargo cache (`$HOME/.cargo/registrysrc`). The build script would then put its output in that cached source directory because of lalrpop/lalrpop#280. Later runs of `cargo vendor` then copy the source from that directory, including the generated file.

**Comment by sgodwincs** [comment] 2018-03-14 20:29
I'm going to keep this open until [lalrpop/lalrpop#333](https://github.com/lalrpop/lalrpop/issues/333) has been dealt with.

**Comment by sgodwincs** [comment] 2018-03-23 22:51
I'm currently trying to get a new version out, but there's a problem with the `include!` used. I opened an issue in lalrpop ([#350](https://github.com/lalrpop/lalrpop/issues/350))

**Comment by Yoric** [comment] 2018-04-05 08:47
Lalrpop is just issued a fixed version. @sgodwincs Could you give it a try?

Barring any accident, this is the last blocker for https://bugzilla.mozilla.org/show_bug.cgi?id=1437004, so I'm eager to land it :)

**Comment by sgodwincs** [comment] 2018-04-05 10:37
@Yoric Version 0.6.0 has been released. The only change you should have to make is that the `Parser` struct has been removed, and you can just directly call the `parse_string` function.

Let me know if there are anymore problems, I'm going to close this for now.

**Closed by sgodwincs** 2018-04-05 10:37 UTC

**Comment by Yoric** [comment] 2018-04-06 19:46
As far as I can tell, this does the trick.

Thanks!
